<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="editelections.aspx.cs" Inherits="online_voting_portal.editelections" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Edit Elections</title>
</head>
<body>
    <form id="form1" runat="server">
        <!--Nav bar-->
        <nav class="teal" role="navigation">
            <div class="nav-wrapper container">
                <a id="logo-container" href="Home.aspx" class="brand-logo">Home</a>
                <ul class="right hide-on-med-and-down">
                    <li><a href="#">ADD ELECTIONS</a></li>
                    <li><a href="#">EDIT ELECTIONS</a></li>
                    <li><a href="#">ADD CANDIDATES</a></li>
                </ul>
            </div>
        </nav>
        <br /> <br />
        <div class="container">
            <h4><strong>EDIT YOUR ELECTIONS HERE:</strong></h4>
            <div class="row">
                <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            <Columns>
                <asp:BoundField DataField="id" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="id" />
                <asp:BoundField DataField="title" HeaderText="Title" SortExpression="title" />
                <asp:BoundField DataField="starttime" HeaderText="Start" SortExpression="starttime" />
                <asp:BoundField DataField="endtime" HeaderText="End" SortExpression="endtime" />
                <asp:BoundField DataField="descriptionelection" HeaderText="Description" SortExpression="descriptionelection" />
            </Columns>
        </asp:GridView>
            </div>
        </div>
    </form>
</body>
</html>